# Generated by Django 3.1 on 2020-11-27 02:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('nombre_local', models.CharField(max_length=600, primary_key=True, serialize=False)),
                ('estacionalidad', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Animal',
            fields=[
                ('nombre_grupo_animal', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Familia_Animal',
            fields=[
                ('nombre_familia_animal', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('grupo_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.grupo_animal')),
            ],
        ),
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('id_experto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_experto', models.CharField(max_length=200)),
                ('apellido_experto', models.CharField(max_length=200)),
                ('institucion_experto', models.CharField(max_length=300)),
                ('identificacion_experto', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Especie_Animal',
            fields=[
                ('nombre_especie_animal', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('familia_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.familia_animal')),
            ],
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id_avistamiento', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('fotografia', models.ImageField(upload_to='')),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.especie_animal'),
        ),
    ]
