# Generated by Django 3.1 on 2020-11-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201124_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nombre_local',
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='especie_animal',
            name='nombre_especie_animal',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='familia_animal',
            name='nombre_familia_animal',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='grupo_animal',
            name='nombre_grupo_animal',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
